export const ERROR_CODES = {
  INVALID_ROOM: "INVALID_ROOM",
  ROOM_FULL: "ROOM_FULL",
  GAME_STARTED: "GAME_STARTED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_WORD: "INVALID_WORD",
  TIMEOUT: "TIMEOUT",
};
