# fly.toml app configuration file generated for nimstreak-api
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nimstreak-api'
primary_region = 'lhr'

[build]

[env]
  PORT = "8080"
  NIMIQ_NETWORK = "mainnet"
  NIMIQ_NETWORK_ID = "24"
  NIMIQ_RPC_URL = "https://rpc.nimiqwatch.com"
  NIMIQ_TREASURY_ADDRESS = "NQ68 LS47 5LF6 C7CU MVB6 KL55 YSFG PEXJ ADJ0"
  MIN_STAKE_NIM = "0.5"
  MAX_STAKE_NIM = "100"
  DEFAULT_STAKE_NIM = "1"
  TREASURY_FEE_PERCENT = "10"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
